# Generated by Django 4.1.7 on 2023-04-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='thumb',
        ),
    ]
